#!/usr/bin/env python3
import rospy
from std_msgs.msg import String

rospy.init_node('t_even_numbers')
pub = rospy.Publisher('chat_topic_en', String, queue_size=10)
rate = rospy.Rate(10)

def start_talker():
	en_str = 0
	msg = String()
	while not rospy.is_shutdown():
	
        	rospy.loginfo(en_str)

        	msg.data = en_str
        	pub.publish(msg)
        	en_str = en_str + 2

        	rate.sleep()

try:
    start_talker()
except (rospy.ROSInterruptException, KeyboardInterrupt):
    rospy.logerr('Exception catched')
